### PR TITLE
Make `Client` and `ClientMultiWorkspace` factory methods accept only keyword arguments

### LINKED ISSUE #85: Make `Client` and `ClientMultiWorkspace` factory methods accept only keyword arguments

### PR DESCRIPTION
**Pull request by andrii-balitskyi**
closes https://github.com/seamapi/ruby-next/issues/85

- **Client factory methods should accept keyword-only args**
- **ClientMultiWorkspace factory methods should accept keyword-only args**
- **Fix tests**

### CODE REVIEW

**Comment by razor-x** [comment]
The factory functions normally take required positional arguments, why are we changing it for ruby?

**Comment by andrii-balitskyi** [comment]
@razor-x We had a discussion (can't find it right now) about this, and IIRC we agreed to make all arguments keyword-only because Ruby doesn't support both positional and keyword for the same argument at the same time. But I'm open to making factory function required arguments positional.

**Comment by razor-x** [comment]
> @razor-x We had a discussion (can't find it right now) about this, and IIRC we agreed to make all arguments keyword-only because Ruby doesn't support both positional and keyword for the same argument at the same time. But I'm open to making factory function required arguments positional.

@andrii-balitskyi I think ruby does support this, as I was able to get this to run:

```rb
def f(a, b:)
  a + b
end

puts f(1, b: 2)
```

**Comment by andrii-balitskyi** [comment]
@razor-x gotcha. Ok, we can close this PR and the relevant issue as irrelevant then.

**Pull request closed without merging**
